import from "radix-ui" { Tooltip as TooltipPrimitive }

def:pub TooltipProvider(props: any) -> JsxElement {
    delayDuration = props["delayDuration"] or 0;
    return
        <TooltipPrimitive.Provider
            {**props}
            data-slot="tooltip-provider"
            delayDuration={delayDuration}
        />;
}

def:pub Tooltip(props: any) -> JsxElement {
    return <TooltipPrimitive.Root data-slot="tooltip" {**props}/>;
}

def:pub TooltipTrigger(props: any) -> JsxElement {
    return <TooltipPrimitive.Trigger data-slot="tooltip-trigger" {**props}/>;
}

def:pub TooltipContent(props: any) -> JsxElement {
    sideOffset = props["sideOffset"] or 0;
    return
        <TooltipPrimitive.Portal>
            <TooltipPrimitive.Content
                {**props}
                data-slot="tooltip-content"
                sideOffset={sideOffset}
                className={cn(
                    "data-open:animate-in data-open:fade-in-0 data-open:zoom-in-95 data-[state=delayed-open]:animate-in data-[state=delayed-open]:fade-in-0 data-[state=delayed-open]:zoom-in-95 data-closed:animate-out data-closed:fade-out-0 data-closed:zoom-out-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 rounded-md px-3 py-1.5 text-xs bg-foreground text-background z-50 w-fit max-w-xs origin-(--radix-tooltip-content-transform-origin)",
                    props["className"]
                )}
            >
                {props["children"]}
                <TooltipPrimitive.Arrow
                    className="size-2.5 translate-y-[calc(-50%-2px)] rotate-45 rounded-[2px] bg-foreground fill-foreground z-50 translate-y-[calc(-50%_-_2px)]"
                />
            </TooltipPrimitive.Content>
        </TooltipPrimitive.Portal>;
}
